---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: php-apache
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  minReplicas: 2
  maxReplicas: 20
  metrics:
  - type: Object
    object:
      metricName: zopa_topic
      target:
        apiVersion: v1
        kind: Service
        name: confluentic-kafka-exporter
      targetValue: 17

